from django.contrib import admin
from backend.models import Sexo, Perfiles, Rutas, Circuitos, Categorias, Subcategorias, Pais, Ciudades, Lugares, Coordenadas,Ranking, Roles, Permisos, Galerias, RedesSociales, Tag, Email, Telefonos

admin.site.register(Sexo)
admin.site.register(Perfiles)
admin.site.register(Rutas)
admin.site.register(Circuitos)
admin.site.register(Categorias)
admin.site.register(Subcategorias)
admin.site.register(Pais)
admin.site.register(Ciudades)
admin.site.register(Lugares)
admin.site.register(Coordenadas)
admin.site.register(Ranking)
admin.site.register(Roles)
admin.site.register(Permisos)
admin.site.register(Galerias)
admin.site.register(RedesSociales)
admin.site.register(Tag)
admin.site.register(Email)
admin.site.register(Telefonos)